<?php /** @var \App\Controller\Actors $controller */
namespace App\template;?>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date of birth</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($controller->getActors() as $actorsInfo) : ?>
        <tr>
            <td><?= $actorsInfo['actor_id'] ?></td>
            <td><?= $actorsInfo['first_name'] . ' ' . $actorsInfo['last_name'] ?></td>
            <td><?= $actorsInfo['dob'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>