<?php /** @var \App\View\Renderer $this */ ?>
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Php project</title>
    <meta name="description" content="PHP framework">
    <meta name="author" content="Andrey Mazurenko">
    <link rel="stylesheet" href="../../pub/css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../pub/components/jquery-ui/jquery-ui.min.css">

</head>
<body>
    <div class="container">
        <?php include $this->getTemplate() ?>
    </div>
</body>
</html>
<script src="../../pub/js/jquery-3.5.1.min.js"></script>
<script src="../../pub/js/script.js"></script>
<script src="../../pub/components/jquery-ui/jquery-ui.min.js"></script>
<script src="../../pub/js/SliderRange.js"></script>

